// <auto-generated />
using System;
using Farmacorp.PosExpress.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Farmacorp.PosExpress.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030005807_ProductosMigrations")]
    partial class ProductosMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Farmacorp.PosExpress.Domain.Entities.ErpProducto", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Stock");

                    b.Property<string>("UniqueCodigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdProducto");

                    b.HasIndex("UniqueCodigo")
                        .IsUnique()
                        .HasDatabaseName("IX_ErpProductos_UniqueCodigo")
                        .HasFilter("[UniqueCodigo] IS NOT NULL");

                    b.ToTable("ErpProductos", null, t =>
                        {
                            t.HasCheckConstraint("CK_ErpProductos_Costo", "[Costo] >= 0");

                            t.HasCheckConstraint("CK_ErpProductos_Stock", "[Stock] >= 0");
                        });
                });

            modelBuilder.Entity("Farmacorp.PosExpress.Domain.Entities.ExpProducto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaVencimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Observaciones");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Precio");

                    b.HasKey("IdProducto");

                    b.ToTable("ExpProductos", (string)null);
                });

            modelBuilder.Entity("Farmacorp.PosExpress.Domain.Entities.ErpProducto", b =>
                {
                    b.HasOne("Farmacorp.PosExpress.Domain.Entities.ExpProducto", "ExpProducto")
                        .WithOne("ErpProducto")
                        .HasForeignKey("Farmacorp.PosExpress.Domain.Entities.ErpProducto", "IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpProducto");
                });

            modelBuilder.Entity("Farmacorp.PosExpress.Domain.Entities.ExpProducto", b =>
                {
                    b.Navigation("ErpProducto")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
